server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location /e9/api/ {
        rewrite ^/e9/api/(.*)$ /$1 break;
        proxy_pass http://backend:8000;
    }

    location /e9/assets/ {
        rewrite ^/e9/(.*)$ /$1 break;
        try_files $uri =404;
    }

    location /e9/ {
        rewrite ^/e9/(.*)$ /$1 break;
        try_files $uri $uri/ /index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}