"""Agrega georef a docentes

Revision ID: e2a9e8bc63d6
Revises: cf97d5e5c492
Create Date: 2026-07-15 09:28:45.701415

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2a9e8bc63d6"
down_revision: Union[str, Sequence[str], None] = "cf97d5e5c492"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "docentes",
        sa.Column("provincia_id_georef", sa.String(length=10), nullable=True),
    )
    op.add_column(
        "docentes",
        sa.Column("localidad_id_georef", sa.String(length=20), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("docentes", "localidad_id_georef")
    op.drop_column("docentes", "provincia_id_georef")
    # ### end Alembic commands ###
